(function(g){
const I=g.IHM=g.IHM||{};
I.ensureProSystems=function(){const s=I.state;s.scoutNetwork=s.scoutNetwork||{region:"Europe",points:3,board:[],lastRefresh:-1};s.negotiations=s.negotiations||{};s.teamMetrics=s.teamMetrics||{shotsFor:0,shotsAgainst:0};s.trophyRoom=s.trophyRoom||[];s.media=s.media||{pressure:25,lastHeadline:""}};
I.prospectNames=["Luka Steiner","Emil Nyberg","Mason Clarke","Noel Hart","Timo Berger","Aaro Koski","Matteo Rossi","Leon Frei","Evan Brooks","Mikael Lund","Jonas Kern","Alexei Morozov"];
I.refreshScoutBoard=function(){I.ensureProSystems();if(I.state.scoutNetwork.lastRefresh===I.state.round&&I.state.scoutNetwork.board.length)return;const bonus=(I.state.facilities.academy-1)*2;I.state.scoutNetwork.board=Array.from({length:6},(_,i)=>{const age=I.rnd(17,21),ovr=I.rnd(61,72)+Math.floor(bonus/3),pot=I.clamp(ovr+I.rnd(8,20)+bonus,70,94),pos=["C","LW","RW","D","G"][I.rnd(0,4)];return{id:I.state.seasonYear*10000+I.state.round*100+i+9000,name:I.prospectNames[(i+I.state.round)%I.prospectNames.length],age,pos,ovr,potential:pot,region:"Europe",scouted:false,certainty:I.rnd(45,68),cost:35000+I.rnd(0,4)*10000}});I.state.scoutNetwork.lastRefresh=I.state.round;I.save()};
I.scoutProspect=function(id){I.ensureProSystems();const p=I.state.scoutNetwork.board.find(x=>x.id===Number(id));if(!p||I.state.scoutNetwork.points<=0)return false;I.state.scoutNetwork.points--;p.scouted=true;p.certainty=I.clamp(p.certainty+I.rnd(20,32)+(I.state.facilities.academy-1)*3,0,100);I.managerXP(3);I.save();return true};
I.signProspect=function(id){const p=I.state.scoutNetwork.board.find(x=>x.id===Number(id));if(!p||!p.scouted||I.state.budget<p.cost)return false;I.addMoney(-p.cost,`Prospect ${p.name}`);const pl={id:p.id,pos:p.pos,name:p.name,age:p.age,ovr:p.ovr,shot:p.pos==="G"?0:p.ovr,pass:p.pos==="G"?0:p.ovr,skate:p.pos==="G"?0:p.ovr,def:p.pos==="G"?0:p.ovr,role:"Prospect",potential:p.potential};I.state.players.push(pl);I.state.rosterIds.push(pl.id);I.state.conditions[pl.id]={energy:95,form:72,happiness:88,injury:0,xp:0};I.state.contracts[pl.id]={salary:4500,years:3};I.state.playerStats[pl.id]={gp:0,g:0,a:0,pts:0,pim:0,plusMinus:0,shots:0,sv:0,sa:0,so:0};I.state.careerStats[pl.id]={gp:0,g:0,a:0,pts:0,pim:0,plusMinus:0,shots:0,sv:0,sa:0,so:0,seasons:0};I.state.scoutNetwork.board=I.state.scoutNetwork.board.filter(x=>x.id!==pl.id);I.addNews(`🌟 Prospect ${pl.name} unterschreibt.`);I.save();return true};
I.openTransferNegotiation=function(id){I.ensureProSystems();const p=I.state.market.find(x=>x.id===Number(id));if(!p)return null;const asking=p.price||Math.max(50000,(p.ovr-68)*45000),n={id:p.id,asking,offer:Math.round(asking*.86/5000)*5000,status:"open",rounds:0};I.state.negotiations[p.id]=n;I.save();return n};
I.submitTransferOffer=function(id,offer){const p=I.state.market.find(x=>x.id===Number(id)),n=I.state.negotiations[Number(id)]||I.openTransferNegotiation(id);if(!p||!n)return{ok:false,msg:"Verhandlung nicht verfügbar"};offer=Number(offer);n.offer=offer;n.rounds++;if(offer>=n.asking*(n.rounds>=2?.93:.97)){n.status="accepted";p.price=offer;const r=I.buyPlayer(p.id);return r.ok?{ok:true,msg:"Transfer akzeptiert"}:{ok:false,msg:r.msg}}if(n.rounds>=3){n.status="rejected";return{ok:false,msg:"Club beendet die Verhandlung"}}n.asking=Math.max(Math.round(n.asking*.96/5000)*5000,Math.round(offer*1.06/5000)*5000);I.save();return{ok:false,msg:`Gegenangebot: ${I.money(n.asking)}`,counter:n.asking}};
I.matchPreview=function(){const f=I.nextUserGame();if(!f)return null;const opp=f.home===I.USER?f.away:f.home,t=I.team(opp),user=I.teamOverall(),enemy=t?.rating||75,diff=user-enemy;return{fixture:f,opp,rival:I.isRival(opp),user,enemy,edge:diff>=3?"Vorteil Frost City":diff<=-3?"Schweres Match":"Ausgeglichen",key:I.getRoster().filter(p=>p.pos!=="G").sort((a,b)=>I.effective(b)-I.effective(a))[0]}};
I.healthReport=function(){const r=I.getRoster();return{injured:r.filter(p=>I.condition(p.id).injury>0),tired:r.filter(p=>I.condition(p.id).energy<70),readiness:Math.round(r.reduce((s,p)=>s+I.condition(p.id).energy,0)/Math.max(1,r.length))}};
I.powerRankings=function(){return I.sortedTable().map((x,i)=>({...x,power:Math.round((I.team(x.name)?.rating||75)+(x.w-x.l)*.35+(x.gf-x.ga)*.05),trend:i<3?"▲":i>6?"▼":"–"})).sort((a,b)=>b.power-a.power)};
I.addTrophy=function(type,label){I.ensureProSystems();if(!I.state.trophyRoom.some(x=>x.season===I.state.seasonYear&&x.type===type))I.state.trophyRoom.unshift({type,label,season:I.state.seasonYear,date:Date.now()})};
I.proTick=function(){I.ensureProSystems();I.state.scoutNetwork.points=Math.min(5,I.state.scoutNetwork.points+1);const rank=I.rank();I.state.media.pressure=I.clamp(20+(rank-1)*5+(I.state.reputation>50?8:0),10,90);I.state.media.lastHeadline=rank<=3?"Frost City mischt im Titelrennen mit":rank>=8?"Krise? Druck auf Frost City wächst":"Frost City kämpft um die Playoffs";I.refreshScoutBoard();I.checkAchievements();I.save()};
})(window);